### ISSUE TITLE
Can't cancel (abort) print from pause

### ISSUE THREAD

**Issue by Lorraine1000** [CR6Community/CR-6-touchscreen#32] opened 2021-02-22 00:07 UTC
After pausing a print, it's not possible to completely cancel the print from pausing. Touchscreen gets stuck in the "Confirm abort" dialog and does not register a tap to the "Confirm" button. Bed and nozzle stay heated, fans stay on. Power cycling the printer resolved the problem. Latest generally available version installed ("Happy new year edition, Rev. 5" iirc).

**Comment by Thinkersbluff** [comment] 2021-02-22 03:49
May be a duplicate of iClosed Marlin Issue#181? https://github.com/CR6Community/Marlin/issues/181

**Comment by Sebazzz** [comment] 2021-02-22 07:07
This appears to be a duplicate indeed. Feel free to re-open if it is not.

**Closed as completed by Sebazzz** 2021-02-22 07:07 UTC
Labels: duplicate
